apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs
  minReplicas: 10
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilizationPercentage: 50
      name: memory
      target:
        type: Utilization
        averageUtilizationPercentage: 60
