apiVersion: version1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: 540174626130.dkr.ecr.us-east-2.amazonaws.com/paytm_repo:nodejs_latest
        ports:
        - containerPort: 8080
